apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: github-exporter-pull-secret
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
